### PR TITLE
Adding Dub Delay and Envelope Delay

### PR DESCRIPTION
**Pull request by djmoffat**
Have run successfully on OwlSim to test thoroughly and also tested on Owl.

### CODE REVIEW

**Comment by pingdynasty** [comment]
good stuff - I'll check this out as soon as I have a moment.
Meanwhile, pls create entries for the new patches on the website -
http://hoxtonowl.com/patch-library/
Link to your own github repo files for now, we can change that later.

**Comment by pingdynasty** [comment]
ok merged, you can link to the main repo if you like!

**Comment by djmoffat** [comment]
Great, thanks.

And I appreciate that this is not by the end of August as I said it would be, but I am working on a Chorus too, so that should be fixed fairly soon (It is just a little buggy atm)

Cheers
---
Dave Moffat
07969375889
djmoffat@gmail.com

**Comment by djmoffat** [comment]
Hello Martin,

I have tried setting up an account for the Patch Library, but I am not receiving emails to set a password or confirm the account.
Many thanks
—
Dave Moffat
07969375889
me@davemoffat.com

**Comment by marsus** [comment]
You've checked your spamcan?
Does password recover work?
http://hoxtonowl.com/lostpassword/

Once logged in, go to Patches / My Patches / Add a new patch.

**Comment by djmoffat** [comment]
A lost password allowed me to reset it.

Thanks
—
Dave Moffat
07969375889
me@davemoffat.com

**Comment by pingdynasty** [comment]
cool - I added CircularBuffer and ToneFilter file dependencies, so they
both now work with the online compiler.

cheers David,

Martin

**Pull request merged**
